version: '3.9'

services: 
    server:
        container_name: 'node'
        build: .
        ports: 
            - '5000:5000'
    db:
        container_name: 'postgres'
        image: 'postgres'
        ports: 
            - '4321:5432'
        environment: 
            POSTGRES_PASSWORD: '123456'
            POSTGRES_USER: 'DOCKER'
    pgadmin:
        image: dpage/pgadmin4
        environment: 
            PGADMIN_DEFAULT_EMAIL: "seuemail@email.com"
            PGADMIN_DEFAULT_PASSWORD: "senha1"
        ports: 
            - "5001:80"
        depends_on: 
            - db
